services:
    Styleflasher\ObfuscatorBundle\Twig\ObfuscatorExtension:
        class: Styleflasher\ObfuscatorBundle\Twig\ObfuscatorExtension
        tags:
            - { name: twig.extension }

    Styleflasher\ObfuscatorBundle\Twig\EmailObfuscator:
        class: Styleflasher\ObfuscatorBundle\Twig\EmailObfuscator
        tags:
            - { name: twig.runtime }
